<?php
/**
 * Điểm Nhấn (GS)
 * This file dynamic info the theme.
 *
 * @package Điểm Nhấn (CS)
 * @author  Media (GFS)
 * @license GPL-2.0+
 * @link    http://www.studiopress.com/
 */

//* Begin theme data
$NZ = array(
    'info'                      => array(
        'logo'                  => get_field('info_logo','option'),
        'favicon'               => get_field('info_favicon','option'),
        'hotline'               => get_field('info_hotline','option'),
        'google_maps'           => get_field('info_google_maps','option')
    ),
    'contact'                   => array(
        'name'                  => get_field('contact_name','option'),
        'address'               => get_field('contact_address','option'),
        'phone'                 => get_field('contact_phone','option'),
        'fax'                   => get_field('contact_fax','option'),
        'email'                 => get_field('contact_email','option'),
        'weblink'               => get_field('contact_weblink','option')
    ),
    'social'                    => array(
        'facebook'              => get_field('social_facebook','option'),
        'pinterest'             => get_field('social_pinterest','option'),
        'twitter'               => get_field('social_twitter','option'),
        'youtube'               => get_field('social_youtube','option'),
        'google_plus'           => get_field('social_google_plus','option')
    )
);

//* Begin theme option
if( function_exists('acf_add_options_page') ) {
    acf_add_options_page(array(
        'page_title'    => __('General Settings','diemnhan'),
        'menu_title'    => __('Interface Config','diemnhan'),
        'menu_slug'     => 'nz-interface',
        'capability'    => 'edit_posts',
        'redirect'      => false
    ));
    acf_add_options_sub_page(array(
        'menu_title'    => __('Images','diemnhan'),
        'page_title'    => __('Display Image','diemnhan'),
        'parent_slug'   => 'nz-interface',
        'menu_slug'     => 'nz-interface-images'
    ));
    acf_add_options_sub_page(array(
        'menu_title'    => __('Products','diemnhan'),
        'page_title'    => __('Display Product','diemnhan'),
        'parent_slug'   => 'nz-interface',
        'menu_slug'     => 'nz-interface-products'
    ));
    acf_add_options_sub_page(array(
        'menu_title'    => __('Contacts','diemnhan'),
        'page_title'    => __('Contact Detail','diemnhan'),
        'parent_slug'   => 'nz-interface',
        'menu_slug'     => 'nz-interface-contacts'
    ));
}

//* Metadata
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
    'key' => 'group_5902a6bd8419a',
    'title' => __('General Setting','diemnhan'),
    'fields' => array (
        array (
            'key' => 'field_5902a6bdc9463',
            'label' => __('General Setting','diemnhan'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_5902a6bdcd13c',
            'label' => __('Logo','diemnhan'),
            'name' => 'info_logo',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'preview-image',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_5902a6bdd0e3f',
            'label' => __('Favicon','diemnhan'),
            'name' => 'info_favicon',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'preview-image',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_5902a6bdd135f',
            'label' => __('Hotline','diemnhan'),
            'name' => 'info_hotline',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5902a6bdd175b',
            'label' => __('Google Maps','diemnhan'),
            'name' => 'info_google_maps',
            'type' => 'google_map',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'center_lat' => '',
            'center_lng' => '',
            'zoom' => 15,
            'height' => '',
        ),
        array (
            'key' => 'field_5902a6bdd1b2c',
            'label' => __('Slider Home','diemnhan'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_5902a6bdd1f0e',
            'label' => __('List Images','diemnhan'),
            'name' => 'home_slide_images',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array (
                array (
                    'key' => 'field_5902a6be56ada',
                    'label' => __('Image','diemnhan'),
                    'name' => 'home_slide_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'preview-image',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
            ),
        ),
        array (
            'key' => 'field_5902a6bdd2315',
            'label' => __('Contact','diemnhan'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_5902a6bdd270b',
            'label' => __('Company','diemnhan'),
            'name' => 'contact_name',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5902a6bdd2aee',
            'label' => __('Address','diemnhan'),
            'name' => 'contact_address',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5902a6bdd2f37',
            'label' => __('Phone','diemnhan'),
            'name' => 'contact_phone',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5902a6bdd32f2',
            'label' => __('Fax','diemnhan'),
            'name' => 'contact_fax',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5902a6bdd36a9',
            'label' => __('Email','diemnhan'),
            'name' => 'contact_email',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5902a6bdd3a90',
            'label' => __('Website','diemnhan'),
            'name' => 'contact_weblink',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array (
            'key' => 'field_5902a6bdd3ea1',
            'label' => __('Social','diemnhan'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_5902a6bdd4267',
            'label' => __('Facebook','diemnhan'),
            'name' => 'social_facebook',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array (
            'key' => 'field_5902a6bdd464c',
            'label' => __('Google Plus','diemnhan'),
            'name' => 'social_google_plus',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array (
            'key' => 'field_5902a6bdd4a33',
            'label' => __('Twitter','diemnhan'),
            'name' => 'social_twitter',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array (
            'key' => 'field_5902a6bdd4e1d',
            'label' => __('Youtube','diemnhan'),
            'name' => 'social_youtube',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array (
            'key' => 'field_5902a6bdd5204',
            'label' => __('Pinterest','diemnhan'),
            'name' => 'social_pinterest',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'nz-interface',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));

endif;

